version: '3'
services:
  # proxy-ui:
  #   image: proxy-ui:latest
  #   build:
  #     context: ./proxy-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  skale-proxy:
    environment:
      ETH_ENDPOINT: ${ETH_ENDPOINT}
    image: skale-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      -  ./data:/data
      -  ./www:/www
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped
  nginx:
    image: nginx:1.20.2
    container_name: skale_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/usr/share/nginx/www/files
      - ./config/nginx.conf:/etc/nginx/nginx.conf
