version: '3'
services:
  skale-proxy:
    environment:
      - PROXY_FULL_HOST_NAME
      - ETH_ENDPOINT
    image: skalenetwork/skale-proxy:develop-latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  /dev/urandom:/dev/random
      -  ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped

