version: '3'
services:
  skale-proxy:
    environment:
      ETH_ENDPOINT: ${ETH_ENDPOINT}
      HEARTBEAT_URL: ${HEARTBEAT_URL}
    image: skale-proxy:latest
    container_name: proxy_admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/proxy/data
      - ./www:/usr/src/proxy/www
      - ./conf:/usr/src/proxy/conf/
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    restart: unless-stopped
  nginx:
    image: nginx:1.20.2
    container_name: proxy_nginx
    network_mode: host
    volumes:
      - ./data:/data
      - ./www:/usr/share/nginx/www/files
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf/
    logging:
      driver: "json-file"
      options:
        max-file: "200"
        max-size: "500m"
  metrics:
    environment:
      ETH_ENDPOINT: ${ETH_ENDPOINT}
      NETWORK_NAME: ${NETWORK_NAME}
    image: metrics:latest
    container_name: metrics
    build:
      context: ./metrics
      dockerfile: Dockerfile
    volumes:
      - ./www:/usr/src/metrics/www
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: unless-stopped