services:
  skale-proxy:
    environment:
      ETH_ENDPOINT: ${ETH_ENDPOINT}
      HEARTBEAT_URL: ${HEARTBEAT_URL}
    image: skale-proxy:latest
    container_name: proxy_admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/proxy/data
      - ./www:/usr/src/proxy/www
      - ./conf:/usr/src/proxy/conf/
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
    restart: unless-stopped

  nginx:
    image: nginx:1.24.0
    container_name: proxy_nginx
    network_mode: host
    volumes:
      - ./data:/data
      - ./www:/usr/share/nginx/www/files
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf/
    logging:
      driver: "json-file"
      options:
        max-file: "200"
        max-size: "500m"

  metrics:
    environment:
      ETH_ENDPOINT: ${ETH_ENDPOINT}
      NETWORK_NAME: ${NETWORK_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_DATABASE: metrics
    image: metrics:latest
    container_name: metrics
    build:
      context: ./metrics
      dockerfile: Dockerfile
    volumes:
      - ./www:/usr/src/metrics/www
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - proxy

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=metrics
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - proxy
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  proxy:
    driver: bridge
