version: '3'
services:
  skale-proxy:
    environment:
      - PROXY_FULL_HOST_NAME=api.skalenodes.com
      - ETH_ENDPOINT=https://mainnet.infura.io/v3/99a12a3b78e54627a8aa694bb94dce69
    image: skale-proxy215
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  /dev/urandom:/dev/random
      -  ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped

