version: '3'
services:
  proxy-ui:
    image: proxy-ui:latest
    container_name: proxy_ui
    build:
      context: ./proxy-ui
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  skale-proxy:
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ETH_ENDPOINT: ${ETH_ENDPOINT}
    image: skale-proxy:latest
    container_name: proxy_admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      -  ./data:/usr/src/proxy/data
      -  ./www:/usr/src/proxy/www
      - ./conf:/usr/src/proxy/conf/
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "4"
    restart: unless-stopped
  nginx:
    image: nginx:1.20.2
    container_name: proxy_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  ./data:/data
      - ./www:/usr/share/nginx/www/files
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf/
