name: Test proxy
on: [push, pull_request]

jobs:
  test_proxy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      ENDPOINT: ${{ secrets.ENDPOINT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MANAGER_TAG: "1.9.3-beta.0"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install python dependencies
      run: bash ./scripts/install_python_dependencies_dev.sh
    - name: Lint with flake8
      run: flake8 .
